name: InspectCode

on: [push, pull_request, workflow_dispatch]
  
jobs:
  inspect-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Display dotnet version
        run: dotnet --version

      - name: Annotate
        # You may pin to the exact commit or the version.
        uses: JetBrains/ReSharper-InspectCode@v0.9
        with:
          solution: ./RoundaboutBlog.sln

    permissions:
      security-events: write
