name: InspectCode

on: [workflow_dispatch]
  
jobs:
  inspect-code:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Display dotnet version
        run: dotnet --version

      - name: Run InspectCode
        uses: JetBrains/ReSharper-InspectCode@v0.9
        with:
          solution: ./RoundaboutBlog.sln
          output: inspectcode-result.xml 

      - name: Upload InspectCode Report
        uses: actions/upload-artifact@v4
        with:
          name: inspectcode-report
          path: inspectcode-result.xml
