name: .NET Roundabout

on: [push, pull_request]

jobs:
  build:
    name: Build, Test and Run blog

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: roundabout_db
          POSTGRES_PASSWORD: roundabout_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      ConnectionStrings__dbConnection: "Host=localhost;Port=5432;Database=roundabout_db;Username=roundabout_db;Password=roundabout_password"
      EMAIL: 0

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install ef cli tool
      run: dotnet tool install --global dotnet-ef
    - name: Create db
      run: dotnet ef database update --project ./RoundaboutBlog
    - name: Run app
      run: dotnet run --no-restore --no-build --project ./RoundaboutBlog/RoundaboutBlog.csproj &
#    - name: Ensure browsers are installed
#      run: pwsh ./RoundaboutWebTests/bin/Debug/net9.0/playwright.ps1 install --with-deps
#    - name: Test
#      run: dotnet test --no-build --verbosity minimal
#    - name: Run code style analysis
#      run: dotnet format --verify-no-changes --severity warn --verbosity diagnostic
#      
#    - name: Upload Playwright screenshots
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: playwright-screenshots
#        path: ./RoundaboutWebTests/bin/Debug/net9.0/screenshots/

    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Add RobotFramework & BrowserLibrary
      run:  pip install robotframework & pip install robotframework-browser
    - name: Init BrowserLibrary
      run: rfbrowser init
    - name: Run RobotTests
      run: robot --output-dir ./RoundaboutWebTests/RobotKeywordTests/results ./RoundaboutWebTests/RobotKeywordTests/test.robot
    - name: Upload RobotFramework results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-results
        path: ./RoundaboutWebTests/RobotKeywordTests/results